apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-backup-sa
  namespace: devops-app
  annotations:
    azure.workload.identity/client-id: "f5c0e756-c411-4a9f-861b-f7c218469de1"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-app-config
  namespace: devops-app
data:
  BACKUP_STORAGE_ACCOUNT: "devopsappproductionfiles"
  BACKUP_CONTAINER: "files"
  DB_HOST: "devops-app-production-pg.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_NAME: "devopsdb"
  PGSSLMODE: "require"
