resources:
  - ../../base
  - network-policy.yaml
  - pod-disruption-budget.yaml
  - devops-app-sealed-secret.yaml
  - postgres-backup-cronjob.yaml

namespace: devops-app

images:
  - name: devops-app
    newName: hiteshmondaldocker/devops-app
    newTag: "b715c16"

patches:
  - path: backup-config-patch.yaml
