#/monitoring/kube-state-metrics/rbac.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-state-metrics
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-state-metrics
rules:
- apiGroups: [""]
  resources:
    - pods
    - nodes
    - services
    - namespaces
    - configmaps
    # PVCs and PVs added — scraped by default in v2.10.1 but
    # previously missing, silently dropping kube_persistentvolumeclaim_* metrics.
    - persistentvolumeclaims
    - persistentvolumes
  verbs: ["list", "watch"]
- apiGroups: ["apps"]
  resources:
    - deployments
    - statefulsets
    - daemonsets
    - replicasets
  verbs: ["list", "watch"]
# HPA permissions added — this project deploys an HPA
# (kubernetes/base/hpa.yaml). Without list+watch on horizontalpodautoscalers,
# kube_horizontalpodautoscaler_spec_max_replicas and related metrics are absent.
- apiGroups: ["autoscaling"]
  resources:
    - horizontalpodautoscalers
  verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-state-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-state-metrics
subjects:
- kind: ServiceAccount
  name: kube-state-metrics
  namespace: kube-system