ci:bootstrap:
  stage: validate
  image: alpine:latest
  script:
    - echo "🚀 CI pipeline initialized"

variables:
  DEPLOY_TARGET: "local"

stages:
  - validate
  - build
  - deploy-local
  - deploy-prod
  - monitoring
  - loki
  - trivy
  - cleanup

include:
  - local: platform/cicd/gitlab/.gitlab-ci.yml