apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-backup-sa
  namespace: devops-app
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::440597412995:role/devops-app-postgres-backup"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-app-config
  namespace: devops-app
data:
  BACKUP_BUCKET: "devops-app-files-ap-south-1"
  DB_HOST: "devops-app-db.c32qeq6ykatq.ap-south-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "devopsdb"
  PGSSLMODE: "require"
