apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: devops-app
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: "placeholder"
  POSTGRES_PASSWORD: "placeholder"
  POSTGRES_DB: "placeholder"
