apiVersion: v1
kind: Secret
metadata:
  name: devops-app-secrets
  namespace: devops-app
  labels:
    app: devops-app
type: Opaque
stringData:
  DB_USERNAME: "placeholder"
  DB_PASSWORD: "placeholder"
  JWT_SECRET: "placeholder"
  API_KEY: "placeholder"
  SESSION_SECRET: "placeholder"
