# Security/trivy/trivy-scan.yaml - Container vulnerability scanning

apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-operator
  namespace: ${TRIVY_NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trivy-operator
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  - replicationcontrollers
  - services
  - namespaces
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trivy-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trivy-operator
subjects:
- kind: ServiceAccount
  name: trivy-operator
  namespace: ${TRIVY_NAMESPACE}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-config
  namespace: ${TRIVY_NAMESPACE}
data:
  trivy.yaml: |
    # Trivy scan configuration
    scanners:
      - vuln
      - config
      - secret
    
    vulnerability:
      severities:
        - CRITICAL
        - HIGH
        - MEDIUM
      
    report:
      format: json
      
    cache:
      dir: /tmp/trivy/.cache
    
    timeout: 5m
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trivy-cache-pvc
  namespace: ${TRIVY_NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trivy-reports-pvc
  namespace: ${TRIVY_NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: trivy-scan
  namespace: ${TRIVY_NAMESPACE}
spec:
  schedule: "${TRIVY_SCAN_SCHEDULE}"
  timeZone: "Asia/Kolkata"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: trivy-operator
          restartPolicy: OnFailure
          containers:
          - name: trivy
            image: ${DOCKERHUB_USERNAME}/trivy-runner:${TRIVY_IMAGE_TAG}
            env:
              - name: TRIVY_SEVERITY
                value: "${TRIVY_SEVERITY}"
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                cpu: 2
                memory: 2Gi
            volumeMounts:
              - name: scan-reports
                mountPath: /reports
              - name: trivy-cache
                mountPath: /tmp/trivy/.cache
          volumes:
            - name: scan-reports
              persistentVolumeClaim:
                claimName: trivy-reports-pvc
            - name: trivy-cache
              persistentVolumeClaim:
                claimName: trivy-cache-pvc
---
apiVersion: batch/v1
kind: Job
metadata:
  name: trivy-initial-scan
  namespace: ${TRIVY_NAMESPACE}
  labels:
    app: trivy
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: trivy
    spec:
      serviceAccountName: trivy-operator
      restartPolicy: Never
      containers:
      - name: trivy
        image: ${DOCKERHUB_USERNAME}/trivy-runner:${TRIVY_IMAGE_TAG}
        command:
        - sh
        - -c
        - |
          echo "Running initial Trivy scan..."
          echo "Updating vulnerability database..."
          trivy image --download-db-only --timeout 10m || true
          
          echo "Scanning application image: ${DOCKERHUB_USERNAME}/${APP_NAME}:${DOCKER_IMAGE_TAG}"
          trivy image \
            --scanners vuln \
            --severity HIGH,CRITICAL \
            --format json \
            --output /reports/initial-${APP_NAME}.json \
            ${DOCKERHUB_USERNAME}/${APP_NAME}:${DOCKER_IMAGE_TAG}
          
          echo "Initial scan complete"
        env:
        - name: TRIVY_NO_PROGRESS
          value: "true"
        - name: DOCKERHUB_USERNAME
          value: "${DOCKERHUB_USERNAME}"
        - name: APP_NAME
          value: "${APP_NAME}"
        - name: DOCKER_IMAGE_TAG
          value: "${DOCKER_IMAGE_TAG}"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi
        volumeMounts:
        - name: scan-reports
          mountPath: /reports
        - name: trivy-cache
          mountPath: /tmp/trivy/.cache
      volumes:
      - name: scan-reports
        persistentVolumeClaim:
          claimName: trivy-reports-pvc
      - name: trivy-cache
        persistentVolumeClaim:
          claimName: trivy-cache-pvc
