# /Security/trivy/trivy-scan.yaml
# ArgoCD-compatible: all ${VAR} placeholders replaced with hardcoded values.
# Default values match security.sh defaults.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-operator
  namespace: trivy-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trivy-operator
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  - replicationcontrollers
  - services
  - namespaces
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trivy-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trivy-operator
subjects:
- kind: ServiceAccount
  name: trivy-operator
  namespace: trivy-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-config
  namespace: trivy-system
data:
  trivy.yaml: |
    scanners:
      - vuln
      - config
      - secret
    vulnerability:
      severities:
        - CRITICAL
        - HIGH
        - MEDIUM
    report:
      format: json
    cache:
      dir: /tmp/trivy/.cache
    timeout: 5m
---
# ReadWriteOnce — both cache and reports PVCs are only mounted by
# one pod at a time, so RWX is unnecessary and breaks on local cluster
# provisioners (Minikube, Kind, K3s) that only support hostPath/local (RWO).
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trivy-cache-pvc
  namespace: trivy-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trivy-reports-pvc
  namespace: trivy-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: trivy-scan
  namespace: trivy-system
spec:
  schedule: "0 16-22 * * *"
  timeZone: "Asia/Kolkata"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 2700
      template:
        spec:
          serviceAccountName: trivy-operator
          restartPolicy: OnFailure
          containers:
          - name: trivy
            image: hiteshmondaldocker/trivy-runner:1.0
            env:
            - name: TRIVY_SEVERITY
              value: "HIGH,CRITICAL"
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                cpu: 2000m
                memory: 2Gi
            volumeMounts:
            - name: scan-reports
              mountPath: /reports
            - name: trivy-cache
              mountPath: /tmp/trivy/.cache
          volumes:
          - name: scan-reports
            persistentVolumeClaim:
              claimName: trivy-reports-pvc
          - name: trivy-cache
            persistentVolumeClaim:
              claimName: trivy-cache-pvc
---
apiVersion: batch/v1
kind: Job
metadata:
  name: trivy-initial-scan
  namespace: trivy-system
  labels:
    app: trivy
spec:
  activeDeadlineSeconds: 1200
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: trivy
    spec:
      serviceAccountName: trivy-operator
      restartPolicy: Never
      containers:
      - name: trivy
        image: hiteshmondaldocker/trivy-runner:1.0
        command:
        - sh
        - -c
        - |
          echo "Running initial Trivy scan..."
          trivy image --download-db-only --timeout 10m || true
          echo "Scanning application image: hiteshmondaldocker/devops-app:latest"
          trivy image \
            --scanners vuln \
            --severity HIGH,CRITICAL \
            --format json \
            --output /reports/initial-devops-app.json \
            hiteshmondaldocker/devops-app:latest
          echo "Initial scan complete"
        env:
        - name: TRIVY_NO_PROGRESS
          value: "true"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi
        volumeMounts:
        - name: scan-reports
          mountPath: /reports
        - name: trivy-cache
          mountPath: /tmp/trivy/.cache
      volumes:
      - name: scan-reports
        persistentVolumeClaim:
          claimName: trivy-reports-pvc
      - name: trivy-cache
        persistentVolumeClaim:
          claimName: trivy-cache-pvc