# /monitoring/Loki/overlays/local/resources-patch.yaml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
spec:
  template:
    spec:
      containers:
      - name: loki
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 512Mi