#!/usr/bin/env bash
# lib/defaults.sh — Centralised default variable assignments
# Source this after loading .env so .env values take precedence.
# All variables use := (set only if unset or empty).

#  APP 
: "${APP_NAME:=devops-app}"
: "${NAMESPACE:=devops}"
: "${APP_PORT:=8000}"
: "${APP_ENV:=production}"
: "${LOG_LEVEL:=info}"
: "${REPLICAS:=2}"
: "${MIN_REPLICAS:=2}"
: "${MAX_REPLICAS:=10}"
: "${DOCKER_IMAGE_TAG:=latest}"
: "${INGRESS_ENABLED:=true}"
: "${INGRESS_HOST:=devops-app.local}"
: "${APP_PORT:=8000}"

#  DATABASE 
: "${DB_HOST:=localhost}"
: "${DB_PORT:=5432}"
: "${DB_NAME:=devops_db}"
: "${DB_USERNAME:=devops_user}"
: "${DB_PASSWORD:=changeme}"

#  SECRETS 
: "${JWT_SECRET:=changeme-jwt-secret}"
: "${API_KEY:=changeme-api-key}"
: "${SESSION_SECRET:=changeme-session-secret}"

#  DEPLOYMENT 
: "${DEPLOY_TARGET:=local}"
: "${DEPLOY_MODE:=direct}"
: "${BUILD_PUSH:=true}"
: "${DRY_RUN:=false}"
: "${CLOUD_PROVIDER:=aws}"
: "${INFRA_ACTION:=plan}"

#  PROMETHEUS / GRAFANA 
: "${PROMETHEUS_ENABLED:=true}"
: "${PROMETHEUS_NAMESPACE:=monitoring}"
: "${PROMETHEUS_SCRAPE_INTERVAL:=15s}"
: "${PROMETHEUS_SCRAPE_TIMEOUT:=10s}"
: "${PROMETHEUS_RETENTION:=15d}"
: "${PROMETHEUS_STORAGE_SIZE:=10Gi}"
: "${PROMETHEUS_CPU_REQUEST:=200m}"
: "${PROMETHEUS_CPU_LIMIT:=500m}"
: "${PROMETHEUS_MEMORY_REQUEST:=256Mi}"
: "${PROMETHEUS_MEMORY_LIMIT:=512Mi}"
: "${PROMETHEUS_PORT:=9090}"
: "${GRAFANA_ENABLED:=true}"
: "${GRAFANA_PORT:=3000}"
: "${GRAFANA_ADMIN_USER:=admin}"
: "${GRAFANA_ADMIN_PASSWORD:=admin}"
: "${GRAFANA_STORAGE_SIZE:=5Gi}"
: "${GRAFANA_CPU_REQUEST:=100m}"
: "${GRAFANA_CPU_LIMIT:=200m}"
: "${GRAFANA_MEMORY_REQUEST:=128Mi}"
: "${GRAFANA_MEMORY_LIMIT:=256Mi}"
: "${GRAFANA_PORT:=3000}"

#  LOKI 
: "${LOKI_ENABLED:=true}"
: "${LOKI_NAMESPACE:=loki}"
: "${LOKI_VERSION:=3.0.0}"
: "${LOKI_RETENTION_PERIOD:=168h}"
: "${LOKI_STORAGE_SIZE:=10Gi}"
: "${LOKI_SERVICE_TYPE:=ClusterIP}"
: "${LOKI_CPU_REQUEST:=100m}"
: "${LOKI_CPU_LIMIT:=1000m}"
: "${LOKI_MEMORY_REQUEST:=256Mi}"
: "${LOKI_MEMORY_LIMIT:=1Gi}"
: "${LOKI_PORT:=3100}"

#  TRIVY 
: "${TRIVY_ENABLED:=true}"
: "${TRIVY_NAMESPACE:=trivy-system}"
: "${TRIVY_VERSION:=0.57.1}"
: "${TRIVY_SEVERITY:=HIGH,CRITICAL}"
: "${TRIVY_SCAN_SCHEDULE:=0 16-22 * * *}"
: "${TRIVY_CPU_REQUEST:=500m}"
: "${TRIVY_CPU_LIMIT:=2000m}"
: "${TRIVY_MEMORY_REQUEST:=512Mi}"
: "${TRIVY_MEMORY_LIMIT:=2Gi}"
: "${TRIVY_METRICS_ENABLED:=true}"
: "${TRIVY_BUILD_IMAGES:=true}"
: "${TRIVY_IMAGE_TAG:=1.0}"
: "${TRIVY_METRICS_PORT:=8082}"

#  EVIDENTLY / WHYLABS 
: "${EVIDENTLY_ENABLED:=false}"
: "${WHYLABS_ENABLED:=false}"

#  ARGO
: "${ARGOCD_NAMESPACE:=argocd}"
: "${ARGOCD_VERSION:=v2.10.0}"
: "${ARGOCD_ADMIN_PASSWORD:=}"
: "${DEPLOY_TARGET:=local}"
: "${NAMESPACE:=devops-app}"
: "${APP_NAME:=devops-app}"
: "${PROMETHEUS_NAMESPACE:=monitoring}"
: "${LOKI_NAMESPACE:=loki}"
: "${ARGOCD_SYNC_WAVE_ENABLED:=true}"
: "${ARGOCD_LOCAL_PORT:=8080}"

#  INGRESS
: "${INGRESS_ENABLED:=true}"
: "${INGRESS_HOST:=devops-app.local}"

#  NODE EXPORTER 
: "${NODE_EXPORTER_PORT:=9100}"


#  KIND CLUSTER NODE-PORT MAPPINGS 
KIND_APP_NODE_PORT=30080
KIND_METRICS_NODE_PORT=30300
KIND_PROMETHEUS_NODE_PORT=30900
KIND_GRAFANA_NODE_PORT=30430
KIND_HTTP_PORT=8081
KIND_HTTPS_PORT=8443

export APP_PORT PROMETHEUS_PORT GRAFANA_PORT LOKI_PORT \
       TRIVY_METRICS_PORT NODE_EXPORTER_PORT \
       KIND_APP_NODE_PORT KIND_METRICS_NODE_PORT \
       KIND_PROMETHEUS_NODE_PORT KIND_GRAFANA_NODE_PORT \
       KIND_HTTP_PORT KIND_HTTPS_PORT ARGOCD_LOCAL_PORT

export APP_NAME NAMESPACE DOCKERHUB_USERNAME DOCKER_IMAGE_TAG APP_PORT
export APP_ENV LOG_LEVEL REPLICAS MIN_REPLICAS MAX_REPLICAS
export DEPLOY_TARGET K8S_DISTRIBUTION MONITORING_SERVICE_TYPE
export INGRESS_ENABLED INGRESS_HOST INGRESS_CLASS PROMETHEUS_NAMESPACE

export PROMETHEUS_SCRAPE_INTERVAL PROMETHEUS_SCRAPE_TIMEOUT
export PROMETHEUS_CPU_REQUEST PROMETHEUS_CPU_LIMIT
export PROMETHEUS_MEMORY_REQUEST PROMETHEUS_MEMORY_LIMIT
export PROMETHEUS_RETENTION PROMETHEUS_STORAGE_SIZE

export GRAFANA_CPU_REQUEST GRAFANA_CPU_LIMIT
export GRAFANA_MEMORY_REQUEST GRAFANA_MEMORY_LIMIT
export GRAFANA_STORAGE_SIZE GRAFANA_ADMIN_USER GRAFANA_ADMIN_PASSWORD
export GRAFANA_PORT

export LOKI_NAMESPACE TRIVY_NAMESPACE