# /monitoring/loki/base/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - loki-deployment.yaml
namespace: loki
labels:
  - pairs:
      app.kubernetes.io/name: loki
      app.kubernetes.io/part-of: monitoring
    includeSelectors: false
