# ml/pipelines/prefect/retraining_flow.py
#
# Prefect — Automated Retraining Flow
# -------------------------------------
# Prefect is a workflow orchestration tool (similar to Airflow) that lets
# you define tasks and flows in plain Python and run them on a schedule
# or trigger them programmatically.
#
# This flow is the "watchdog" of the MLOps system:
#   1. It checks whether the live model has started to drift (degrade)
#   2. If drift is detected, it re-triggers the Metaflow training pipeline
#
# How it fits in this project:
#   Evidently (drift_detection.py) generates a drift report and a JSON summary.
#   This flow reads that summary and decides whether retraining is needed.
#   run.sh → deploy_mlops() → calls this flow after the first training run.
#
# Run manually:
#   python ml/pipelines/prefect/retraining_flow.py
#
# Run on a Prefect schedule (via Prefect Cloud or local server):
#   prefect deployment build ml/pipelines/prefect/retraining_flow.py:retraining_flow \
#     --name daily-retraining --interval 86400
#   prefect deployment apply retraining_flow-deployment.yaml

import os
import json
import subprocess

from prefect import flow, task


#  Task 1: Check for data drift 
@task(retries=2, retry_delay_seconds=30)
def check_drift() -> bool:
    """
    Reads the Evidently drift summary (monitoring/evidently/reports/drift_summary.json)
    and returns True if drift was detected above the configured threshold.

    The drift threshold is set in ml/configs/deployment.yaml:
      drift_threshold: 0.1   (10% of features have drifted)

    If the summary file doesn't exist yet (e.g. first run), we return False
    so training isn't triggered unnecessarily.
    """
    # Path to the drift report generated by drift_detection.py
    project_root = os.getenv(
        "PROJECT_ROOT",
        os.path.abspath(os.path.join(os.path.dirname(__file__), "../../..")),
    )
    summary_path = os.path.join(
        project_root, "monitoring/evidently/reports/drift_summary.json"
    )
    threshold = float(os.getenv("DRIFT_THRESHOLD", "0.1"))

    if not os.path.exists(summary_path):
        print("[check_drift] No drift summary found — skipping (first run?)")
        return False

    with open(summary_path) as f:
        summary = json.load(f)

    # Evidently stores the share of drifted columns in the summary dict.
    # The exact key path depends on the Evidently version; we use .get() safely.
    drift_share = (
        summary
        .get("metrics", [{}])[0]
        .get("result", {})
        .get("share_of_drifted_columns", 0.0)
    )

    print(f"[check_drift] Drift share = {drift_share:.2%} (threshold = {threshold:.2%})")

    drifted = drift_share > threshold
    if drifted:
        print("[check_drift] ⚠ Drift detected — retraining will be triggered")
    else:
        print("[check_drift] ✓ No significant drift — model is healthy")

    return drifted


#  Task 2: Retrain the model 
@task(retries=1, retry_delay_seconds=60)
def retrain():
    """
    Triggers the Metaflow training pipeline as a subprocess.

    Using subprocess means this task doesn't import sklearn/pandas directly —
    it just starts the training job and waits for it to finish.
    The training job logs its own metrics to Neptune / Comet / MLflow.
    """
    project_root = os.getenv(
        "PROJECT_ROOT",
        os.path.abspath(os.path.join(os.path.dirname(__file__), "../../..")),
    )
    flow_path = os.path.join(
        project_root, "ml/pipelines/metaflow/training_flow.py"
    )

    print(f"[retrain] Starting Metaflow training flow: {flow_path}")

    result = subprocess.run(
        ["python", flow_path, "run"],
        capture_output=True,
        text=True,
        check=True,      # raises CalledProcessError if training fails
    )

    print(result.stdout)
    print("[retrain] Retraining complete")


#  Flow definition 
@flow(
    name="retraining-flow",
    description="Checks for data drift and retrains the model if drift is detected",
)
def retraining_flow():
    """
    Prefect flow that wires check_drift → retrain together.

    Prefect tracks every run of this flow in its UI / database, so you can
    see the history of when drift was detected and when retraining occurred.
    """
    drift_detected = check_drift()

    if drift_detected:
        retrain()
    else:
        print("[retraining_flow] No drift — skipping retraining")


if __name__ == "__main__":
    # Running this file directly triggers one execution of the flow.
    # In production: schedule it via Prefect deployments (see header above).
    retraining_flow()