vars:
  - ../../configs/params.yaml

stages:

  prepare:
    cmd: python ../../../app/src/prepare.py
    deps:
      - ../../../app/src/prepare.py
      - ${dataset.raw_path}
    params:
      - dataset.raw_path
      - dataset.processed_path
    outs:
      - ${dataset.processed_path}


  feature_engineering:
    cmd: python ../../../app/src/features.py
    deps:
      - ../../../app/src/features.py
      - ${dataset.processed_path}
    params:
      - features
    outs:
      - ${dataset.features_path}


  split:
    cmd: python ../../../app/src/split.py
    deps:
      - ../../../app/src/split.py
      - ${dataset.features_path}
    params:
      - dataset.test_size
      - dataset.random_state
    outs:
      - ${dataset.train_path}
      - ${dataset.test_path}


  train:
    cmd: python ../../metaflow/training_flow.py run
    deps:
      - ../../metaflow/training_flow.py
      - ${dataset.train_path}
      - ../../configs/params.yaml
    params:
      - model
      - training
    outs:
      - ${training.model_output}


  evaluate:
    cmd: python ../../../app/src/evaluate.py
    deps:
      - ../../../app/src/evaluate.py
      - ${training.model_output}
      - ${dataset.test_path}
    metrics:
      - ${training.metrics_output}