pipeline {
  agent any

  environment {
    APP_NAME = "devops-app"
    IMAGE_TAG = "${BUILD_NUMBER}"
    KUBE_NAMESPACE = "devops-app"
  }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Docker Login') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'dockerhub-creds',
          usernameVariable: 'DOCKERHUB_USERNAME',
          passwordVariable: 'DOCKERHUB_PASSWORD'
        )]) {
          sh 'echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin'
        }
      }
    }

    stage('Build & Push Image') {
      steps {
        sh '''
          IMAGE=$DOCKERHUB_USERNAME/$APP_NAME:$IMAGE_TAG
          docker build -t $IMAGE ./app
          docker push $IMAGE
        '''
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        sh '''
          IMAGE=$DOCKERHUB_USERNAME/$APP_NAME:$IMAGE_TAG
          kubectl set image deployment/devops-app devops-app=$IMAGE -n $KUBE_NAMESPACE
        '''
      }
    }
  }
}
